# Generated by Django 3.1.3 on 2021-04-24 09:02

import Profile.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Phone', models.IntegerField(validators=[django.core.validators.RegexValidator('[1-9]{1}[0-9]{9}', 'Enter the phone number without 0 and country code.', 'Enter the phone number without 0 and country code.')])),
                ('Image', models.ImageField(default='Default.png', upload_to=Profile.models.profile_file_path)),
                ('College', models.CharField(blank=True, max_length=200)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
