# Generated by Django 3.2.5 on 2021-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
