# Generated by Django 3.1.3 on 2021-04-24 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Problem', models.TextField()),
                ('Answer', models.CharField(max_length=100)),
            ],
        ),
    ]
