# Generated by Django 3.1.3 on 2021-04-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matrix', models.TextField(default='2-d matrix')),
                ('Completed', models.CharField(blank=True, max_length=20)),
                ('Current', models.CharField(default='BINGO', max_length=10)),
                ('End', models.DateTimeField(blank=True)),
                ('Player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('Questions', models.ManyToManyField(related_name='Questions', to='Question.Question')),
            ],
        ),
    ]
