# Generated by Django 3.1.3 on 2021-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Questions',
            field=models.ManyToManyField(blank=True, related_name='Questions', to='Question.Question'),
        ),
    ]
