# Generated by Django 3.1.3 on 2021-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20210424_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='End',
            field=models.DateTimeField(null=True),
        ),
    ]
