# Generated by Django 3.1.3 on 2021-04-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20210424_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='CrtQuestion',
            field=models.CharField(default='One', max_length=100),
        ),
    ]
