# Generated by Django 3.1.3 on 2021-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_game_crtquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
