# Generated by Django 3.1.3 on 2021-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='CrtQuestion',
        ),
        migrations.AddField(
            model_name='game',
            name='Penalty',
            field=models.IntegerField(default=0),
        ),
    ]
