# Generated by Django 3.1.3 on 2021-04-25 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_auto_20210425_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
